# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# - name: Research
#   url: research
#   weight: 30
# - name: Publications
#   url: publication
#   weight: 40
# - name: Notes
#   url: notes
#   weight: 50
# - name: Join
#   url: '#join'
#   weight: 70

main:
  - name: Home
    url: ''
    weight: 10
  - name: News
    url: news
    weight: 20
  - name: People
    url: people
    weight: 60
  - name: Policies
    url: policies
    weight: 70
  - name: Misc
    url: misc
    weight: 75
    hasChildren: true
  - parent: Misc
    name: Upcoming Events
    url: misc/upcoming
    weight: 10
  - name: Contact
    url: '#contact'
    weight: 80
